server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: blood-rel
  profiles:
    active: test

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
    cache: false
  jpa:
    open-in-view: false
    show-sql: true



